name: ✨ Feature Request
description: Suggest a new feature for the Git Palette extension
title: '✨ [FEATURE]: '
labels: ['enhancement']
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: textarea
    id: feature-description
    attributes:
      label: ✨ Feature Description
      description: A clear and concise description of the feature you'd like to see added.
      placeholder: Describe the feature you want...
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: 🎯 Problem Statement
      description: What problem would this feature solve? Is your feature request related to a problem?
      placeholder: What problem does this solve?
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: 💡 Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: How should this feature work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 🔄 Alternative Solutions
      description: Describe any alternative solutions or features you've considered.
      placeholder: What other approaches have you considered?

  - type: textarea
    id: use-cases
    attributes:
      label: 🏷️ Use Cases
      description: Describe specific scenarios where this feature would be helpful
      placeholder: |
        - Use case 1: ...
        - Use case 2: ...
        - Use case 3: ...
    validations:
      required: true

  - type: textarea
    id: user-experience
    attributes:
      label: 🎨 User Experience
      description: How should this feature work from a user's perspective?
      placeholder: Describe the user workflow and interaction...

  - type: dropdown
    id: priority
    attributes:
      label: 📈 Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Really need this
        - Critical - Can't work without it
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: 📋 Additional Context
      description: Add any other context, mockups, screenshots, or examples about the feature request here.
      placeholder: Any mockups, links, or additional information...
